[package]
name = "jd-crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
headless_chrome = "1.0"
scraper = "0.20"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.10"
regex = "1"
